[ldap-users] remove threading
app-sre/qontract-reconcile pull request #1748
Opened 2021-08-05 10:29 UTC by maorfr

part of https://issues.redhat.com/browse/APPSRE-3547

instead of searching user by users, we get all users and find missing ones in memory.

2021-08-05 15:04 UTC, Piojo requested changes
Please note that, while all my comments are correct from an LDAP perspective, I am not familiar with the Python modules - the return structure of `search` may need some adjustments. API docs: https://ldap3.readthedocs.io/en/latest/searches.html

2021-08-05 15:04 UTC, Piojo commented on reconcile/utils/ldap_client.py
> +            dn = r['dn']
Just extract the uid field here.
```suggestion
            uid = r['uid']
```

2021-08-05 16:41 UTC, Piojo commented
I'd be curious to know the new timings. :)

2021-08-09 08:53 UTC, maorfr commented on reconcile/utils/ldap_client.py
> +        _, _, results, _ = client.search(_base_dn, '(&(objectclass=person))')
added `attributes=["uid"]`, thanks! there is no significant difference passing uids or not (4-5 seconds for both ways).

2021-08-09 08:53 UTC, maorfr commented on reconcile/utils/ldap_client.py
> +            dn = r['dn']
thanks!

2021-08-09 08:55 UTC, maorfr commented
time improvement: 2m39s -> 8s (!!!)

2021-08-09 13:08 UTC, Piojo approved these changes
LGTM. A future optimization is to query only for the 700-or-so users known to app-interface instead of the ~10K IDs we may get from querying the entire LDAP subtree. But for now, this is awesome and I bet the LDAP owners will be pleased as well.

2021-08-10 06:15 UTC, maorfr commented
changed the query to only be for the known users, as you suggested. run time is still ~8s, but it's obviously better this way.

2021-08-10 06:17 UTC, merged