Update integration and query to be able to create SNS topic and SNS event notification for S3
app-sre/qontract-reconcile pull request #2052
Opened 2021-12-16 22:24 UTC by OliviaHY

2021-12-17 10:23 UTC, BumbleFeng commented
Could you separate create SNS topic and SNS event notification for S3 into 2 PR?

2021-12-17 14:38 UTC, OliviaHY commented
> Could you separate create SNS topic and SNS event notification for S3 into 2 PR?

Absolutely.

2021-12-20 19:28 UTC, Piojo requested changes
There are merge conflicts. Please rebase and re-submit.

2021-12-20 19:28 UTC, Piojo commented on reconcile/utils/terrascript_client.py
> +    def populate_tf_resource_sns(self, resource, namespace_info):
I'm pretty sure we can add unit tests for this. :)

2022-01-05 15:27 UTC, closed without merging