Logic to retrieve bucket information from new terraform state schema
app-sre/qontract-reconcile pull request #2449
Opened 2022-06-02 13:47 UTC by suzana-nesic

We have implemented a new schema change that displays terraform state information through an account file

Schema setup for a file tf-state-test.yml:
```
---
$schema: /dependencies/terraform-state-1.yml
provider: s3
bucket: someBucket
region: someRegion
integrations:
- integration: terraform-resources
  key:  qontract-reconcile.tfstate
- integration: terraform-tgw-attachements
  key: qontract-reconcile-tgw-attachments.tfstate
```

AWS account file call:
```
terraformState:
  $ref: /aws/app-sre-stage/tf-state-test.yml
```

This MR will implement logic that will check if the new schema changes are present within app-interface and if it is, it will execute logic to retrieve bucket information the new way (looking within app-interface and extracting the information) or the current way (looking within vault to retrieve that information).

Part of [APPSRE-4516](https://issues.redhat.com/browse/APPSRE-4516)

Signed-off-by: Suzana Nesic <snesic@redhat.com>

2022-06-08 11:35 UTC, geoberle commented on reconcile/utils/terrascript_aws_client.py
> +                    integration = terraform_state['integrations']['integration']
`terraform_state["integrations"]` is a list so you need to find the one that matches the currently executed integration provided as the `integration` variable to this function.

2022-06-15 13:18 UTC, janboll requested changes

2022-06-15 13:18 UTC, janboll commented on reconcile/utils/terrascript_aws_client.py
> +# TERRAFORM_STATE_QUERY = """
This comment confused me for a couple of seconds. Do we need to keep it?

2022-06-15 13:18 UTC, janboll commented on reconcile/utils/terrascript_aws_client.py
> +                if not terraform_state:
Would suggest to move declaration of:
- access_key
- secret_key

out of if statement, cause they are the same for both cases.

2022-06-15 13:18 UTC, janboll commented on reconcile/utils/terrascript_aws_client.py
> +                                key=config['{}_key'.format(integration)],
Please use f-string syntax

2022-06-15 13:18 UTC, janboll commented on reconcile/utils/terrascript_aws_client.py
> +                                key=integration + "_key",
Please use f-string syntax

2022-06-15 13:19 UTC, janboll submitted a review, later dismissed

2022-06-22 06:39 UTC, geoberle commented on reconcile/utils/terrascript_aws_client.py
> +            accounts = queries.get_aws_accounts(terraform_state=True)
why query for the accounts again? filtered_accounts already holds the accounts queries in terraform_resources.py and you could query with `terraform_state=True` there

https://github.com/app-sre/qontract-reconcile/blob/826cc8683cba0dccbe9fae677d4c2f04d3c5828c/reconcile/terraform_resources.py#L467

2022-06-22 06:39 UTC, geoberle commented on reconcile/utils/terrascript_aws_client.py
> +                for account in accounts:
remember that you are in a loop over `configs` here. everything you do here, you do for each account, e.g. you create the `Backend` filtered_accounts*filtered_accounts times.

have a look at the context here. the variable `name` is bound to the AWS account name your are currently iterating over. so maybe something like the following could work. please verify with a dry run though

```
for acc in filtered_account:
    if acc.get("name") == name:
        # check on terraformState variable in acc (assuming filtered_accounts was created with  terraform_state=True 
        # and create Backend accordingly
```

2022-06-27 05:57 UTC, geoberle commented on reconcile/utils/terrascript_aws_client.py
> +            region_backend_value = ""
you don't need to declare the variables here. in python, local variables are scoped within the function, so assigning them later in this function will make them available during Backend creation.

2022-06-27 05:57 UTC, geoberle commented on reconcile/utils/terrascript_aws_client.py
> +
consider using the `bucket`, `region` and `key` fields from the account if no 'key' is defined within `terraformState`.
or fail the integration if you `terraformState` is present but no `key` is defined for an integration.

2022-06-30 05:21 UTC, geoberle commented on reconcile/utils/terrascript_aws_client.py
> +
with "no key defined" i meant if the terraformState does not contain information for an integration, try to discover the required information the old way

2022-07-01 13:47 UTC, geoberle reviewed
tiny nit on the test. other great and LGTM!

2022-07-05 21:59 UTC, suzana-nesic commented on reconcile/test/test_utils_terrascript_aws_client.py
> +    assert ts.state_bucket_for_account(integration_name, account_name, config_test)
Added a couple of more tests and changed to compare the values

2022-07-07 14:03 UTC, geoberle approved these changes
LGTM

2022-07-07 15:57 UTC, merged