replace openshift-saas-deploy-wrapper with o-s-d-change-tester
app-sre/qontract-reconcile pull request #2849
Opened 2022-10-06 13:13 UTC by geoberle

# Why

`saas-file-owners` and `openshift-saas-deploy-wrapper` are closely related integrations. `saas-file-owners` creates an input file about saas-file that have changed that is passed to `openshift-saas-deploy-wrapper`, so it can run `openshift-saas-deploy` for each changed saas-file to verify the content.

when we switch from `saas-file-owners` to `change-owners` for self-service approvals, `saas-file-owners` will not run as part of `app-interface` PR checks anymore, so the input `openshift-saas-deploy-wrapper` expects is not there anymore.

# What changed

This MR introduces a new integration `openshift-saas-deploy-change-tester` which takes over the responsibility to run `openshift-saas-deploy` for each changed saas-file. This integration will be able to detect for itself what saas-files changed without the need of `saas-file-owners` passing information. `openshift-saas-deploy-change-tester` is using the dual-bundle `qontract-server` during app-interface PR checks to find the differences in saas-files.

`saas-file-owners` had another responsibility, namely adding a commit to the checked MR about the saas-file target `refs` that changed. This functionality has been moved to `openshift-saas-deploy-change-tester` as well. This means that `saas-file-owners` and `openshift-saas-deploy-wrapper` can be safely disabled during PR checks (and removed later on) when `change-owners` and `openshift-saas-deploy-change-tester` are running instead.

# Alternatives considered

I considered changing `openshift-saas-deploy-wrapper` instead of creating a new integration but leaving both `saas-file-owner` and `openshift-saas-deploy-wrapper` unchanged brings flexibility about when and how to do the switch to the granular permission model with `change-owners`. It even allows reverting an app-interface instance back to using `saas-file-owners` in case of bugs in `change-owners` without reverting code, simply by enabling or disabling integrations for the PR checks. It also allows one app-interface instance running with `change-owners` while another one still runs `saas-file-owner`.

Signed-off-by: Gerd Oberlechner <goberlec@redhat.com>

2022-10-07 08:47 UTC, janboll commented on reconcile/openshift_saas_deploy_change_tester.py
> +def update_mr_with_ref_diffs(
Would love to see a test for this function.

2022-10-07 09:05 UTC, janboll commented
Thank you for the good documentation on this Pull Request. I have one big concern with this PR and that is the reuse of functions from `saas-file-owners` integration. This creates a tight coupling between these two integrations. To make it worse, both integrations have zero test coverage.
My ask here would be to move the shared functionality into a separate module (utils?) and create tests for them.

2022-10-07 09:06 UTC, janboll requested changes

2022-10-07 09:06 UTC, janboll commented on reconcile/openshift_saas_deploy_change_tester.py
> +import sys
Please consider adding some tests for this integration.

2022-10-07 13:52 UTC, geoberle commented
> My ask here would be to move the shared functionality into a separate module (utils?) and create tests for them. 

You are completely right. I will refactored and create the tests.

2022-10-10 11:12 UTC, janboll approved these changes

2022-10-10 11:12 UTC, janboll commented on reconcile/openshift_saas_deploy_change_tester.py
> +import sys
Thank you for adding tests!

2022-10-10 11:37 UTC, merged